[package]
name = "euler_rust"
version = "0.1.0"
authors = ["Joe Dane <joe.dane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.0"
num-integer = "0.1"
num-traits = "0.2"
