[package]
name = "e83"
version = "0.1.0"
authors = ["Joe Dane <joe.dane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

array2d = "0.2.1"
priority-queue = "1.0.5"
