[package]
name = "e96"
version = "0.1.0"
authors = ["Joe Dane <joe.dane@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stringreader = "0.1.1"
log = "0.4.14"
simplelog = "0.10.1"
lazy_static = "1.4.0"