[package]
name = "e94"
version = "0.1.0"
authors = ["Joe Dane <joe.dane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.4.0"
rayon = "1.5"