[package]
name = "e95"
version = "0.1.0"
authors = ["Joe Dane <joe.dane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = 1

[dependencies]
euler_rust = { path = "../euler-rust" }